# This is a basic workflow to help you get started with Actions

name: CI-Python
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.ref }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
s
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APP_NAME: PythonApp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-python:
    env:
      CONFIG_TYPE: Debug
      PYTHON_VERSION: 3.8

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --show-source --statistics --ignore=E251,E501,W605,E402

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest -v --cov=./ --cov-report=json --cov-report=term-missing

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifact
          path: .