name: helm-deploy-python

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: ${{ inputs.environment }}

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: helm-package
        path: .

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - uses: azure/setup-kubectl@v4
      name: Set up Kubectl

    - uses: azure/login@v1.4.3
      id: login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v3
      id: set-context
      with:
        cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}
        resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

    - name: Deploy Helm
      run: |
        helm upgrade --install --atomic  --wait --timeout 3600s --debug kube2py ./kube2py-*.tgz  \
          --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set kube2py.secrets.password="${{ secrets.PASSWORD }}" \
          --set kube2py.secrets.login="${{ secrets.LOGIN }}" \
          --set kube2py.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
          --set global.environment="${{ inputs.environment }}" \
          --set kube2py.image.version="${{ inputs.version }}"
