name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PythonVersion: 3.8
  DockerUsername: ikulyk404
  DockerImageName: kube2py

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PythonVersion }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        cd ../
        flake8 . --show-source --statistics

    - name: Check Complexity
      run: |
        cd ../
        flake8 . --exit-zero --max-complexity=10 --statistics

    - name: Test with pytest
      run: |
        pytest -v --cov-report=term-missing --cov=. --cov-report=json

    - name: Upload python artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-artifacts
        path: .

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: python-artifacts
        path: .

    - name: Build Docker image for DockerHub
      run: |
        docker build -t ${{ env.DockerImageName }} .
        docker tag ${{ env.DockerImageName }} ${{ env.DockerUsername }}/${{ env.DockerImageName }}:${{ github.sha }}

    - name: Push Docker image to DockerHub
      run: |
        echo ${{ secrets.DOCKER_HUB_SECRET }} | docker login -u ${{ env.DockerUsername }} --password-stdin
        docker push ${{ env.DockerUsername }}/${{ env.DockerImageName }}:${{ github.sha }}